Update Dockerfile

diff --git a/mealie/Dockerfile b/mealie/Dockerfile
--- a/mealie/Dockerfile
+++ b/mealie/Dockerfile
@@ -1,44 +1,74 @@
+#============================#
+#  ALEXBELGIUM'S DOCKERFILE  #
+#============================#
+#           _.------.
+#       _.-`    ('>.-`"""-.
+# '.--'`       _'`   _ .--.)
+#    -'         '-.-';`   `
+#    ' -      _.'  ``'--.
+#        '---`    .-'""`
+#               /`
+#=== Home Assistant Addon ===#
+
+#################
+# 1 Build Image #
+#################
+
 ARG BUILD_FROM
 ARG BUILD_VERSION
 FROM ${BUILD_FROM}
 
+##################
+# 2 Modify Image #
+##################
+
+# Correct data path
+# hadolint ignore=DL4006
+RUN grep -rl "/app/data" /app | xargs sed -i 's|/app/data|/data|g'
+
+##################
+# 3 Install apps #
+##################
+
+# Add rootfs
+COPY rootfs/ /
+
+# Modules
+ARG MODULES="00-banner.sh"
+
+# Automatic modules download
+RUN if ! command -v bash >/dev/null 2>/dev/null; then (apt-get update && apt-get install -yqq --no-install-recommends bash || apk add --no-cache bash) >/dev/null; fi \
+    && if ! command -v curl >/dev/null 2>/dev/null; then (apt-get update && apt-get install -yqq --no-install-recommends curl || apk add --no-cache curl) >/dev/null; fi \
+    && mkdir -p /etc/cont-init.d \
+    && for scripts in $MODULES; do curl -L -f -s -S "https://raw.githubusercontent.com/alexbelgium/hassio-addons/master/.templates/$scripts" -o /etc/cont-init.d/"$scripts" || (echo "script failed to install $scripts" && exit 1); done \
+    && chmod -R 755 /etc/cont-init.d || printf '%s\n' "${MODULES}" >/MODULESFILE
+
+# Manual apps
+ENV PACKAGES="jq curl bash nginx"
+
+# Automatic apps & bashio
+RUN if ! command -v bash >/dev/null 2>/dev/null; then (apt-get update && apt-get install -yqq --no-install-recommends bash || apk add --no-cache bash) >/dev/null; fi \
+    && if ! command -v curl >/dev/null 2>/dev/null; then (apt-get update && apt-get install -yqq --no-install-recommends curl || apk add --no-cache curl) >/dev/null; fi \
+    && curl -L -f -s "https://raw.githubusercontent.com/alexbelgium/hassio-addons/master/.templates/automatic_packages.sh" --output /automatic_packages.sh \
+    && chmod 777 /automatic_packages.sh \
+    && eval /./automatic_packages.sh "${PACKAGES:-}" \
+    && rm /automatic_packages.sh || printf '%s\n' "${PACKAGES:-}" > /ENVFILE
+
+################
+# 4 Entrypoint #
+################
+
 RUN \
-    ################
-    # Install apps #
-    ################
-    apk add --no-cache jq curl bash nginx
-
-COPY rootfs /
-
-ARG BASHIO_VERSION=0.13.1
-
-RUN \
-    ##################
-    # Install bashio #
-    ##################
-    mkdir -p /tmp/bashio \
-    && curl -L -f -s "https://github.com/hassio-addons/bashio/archive/v${BASHIO_VERSION}.tar.gz" \
-    | tar -xzf - --strip 1 -C /tmp/bashio \
-    && mv /tmp/bashio/lib /usr/lib/bashio \
-    && ln -s /usr/lib/bashio/bashio /usr/bin/bashio \
-    && rm -rf /tmp/bashio \
-    \
-    ###############
-    # Adapt image #
-    ###############
-    # Correct data path
-    && grep -rl "/app/data" /app | xargs sed -i 's|/app/data|/data|g' \
     # Add custom instructions to run.sh
-    && sed -i '1d' /app/mealie/run.sh \ 
-    && cat /app/mealie/run.sh >> /nginx.txt \
-    && cat /nginx.txt > /app/mealie/run.sh \
+    sed -i '1d' /app/mealie/run.sh \
+    && cat /app/mealie/run.sh >> /run.txt \
+    && cat /run.txt > /app/mealie/run.sh \
     && chmod +x /app/mealie/run.sh
-    # Add custom caddy instructions for ingress
-    # && cat /caddy.txt >> /app/Caddyfile
 
-VOLUME [ "/data" ]
+############
+# 5 Labels #
+############
 
-### LABELS
 ARG BUILD_ARCH
 ARG BUILD_DATE
 ARG BUILD_DESCRIPTION
@@ -52,13 +82,13 @@ LABEL \
     io.hass.arch="${BUILD_ARCH}" \
     io.hass.type="addon" \
     io.hass.version=${BUILD_VERSION} \
-    maintainer="tyjtyj (https://github.com/tyjtyj)" \
+    maintainer="alexbelgium (https://github.com/alexbelgium)" \
     org.opencontainers.image.title="${BUILD_NAME}" \
     org.opencontainers.image.description="${BUILD_DESCRIPTION}" \
     org.opencontainers.image.vendor="Home Assistant Add-ons" \
-    org.opencontainers.image.authors="tyjtyj (https://github.com/tyjtyj)" \
+    org.opencontainers.image.authors="alexbelgium (https://github.com/alexbelgium)" \
     org.opencontainers.image.licenses="MIT" \
-    org.opencontainers.image.url="https://github.com/tyjtyj" \
+    org.opencontainers.image.url="https://github.com/alexbelgium" \
     org.opencontainers.image.source="https://github.com/${BUILD_REPOSITORY}" \
     org.opencontainers.image.documentation="https://github.com/${BUILD_REPOSITORY}/blob/main/README.md" \
     org.opencontainers.image.created=${BUILD_DATE} \
